Repository midusi/PlateUNLP, pull requests merged in 2025-02, with the labels that each got.

#120 :sparkles: :lipstick: Elementos no seleccionables
  app/src/components/organisms/BBImageEditor.tsx
Labels: bug

#121 108 mejora de apariencia botón autodetect
  app/src/components/organisms/BBImageEditor.tsx
  app/src/components/pages/StepSpectrumSegmentation.tsx
Labels: appearance, refactoring

#125 :sparkles: El modelo si o si lleva los BBs hasta los extremos
  app/src/hooks/use-predict-BBs.ts
Labels: bug, enhancement

#126 111 alertas de dependencias
  app/package.json
  app/postcss.config.js
  pnpm-lock.yaml
Labels: security

#130 118 plus fix
  README.md
  app/src/components/molecules/LoadFile.tsx
  app/src/components/organisms/SegmentationUI.tsx
  app/src/components/pages/StepPlateSegmentation.tsx
  app/src/components/pages/StepSpectrumSegmentation.tsx
Labels: bug, documentation, enhancement

#140 :camera_flash: Screenshots
  screenshots/Calibratión(2).png
  screenshots/Calibratión.png
  screenshots/MetadataRetrieval.png
  screenshots/PlateSegmentation(2).png
  screenshots/PlateSegmentation.png
  screenshots/SpectrumSegmentation(2).png
  screenshots/SpectrumSegmentation.png
Labels: documentation

#141 Backend
  app/.gitignore
  app/app.config.ts
  app/package.json
  app/src/lib/trpc.ts
  app/trpc-server.handler.ts
  app/vite.config.ts
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/package.json
  server/package.json
  server/src/routers/index.ts
  server/src/trpc.ts
Labels: enhancement
