Repository midusi/PlateUNLP, pull requests merged in 2025-03, with the labels that each got.

#145 Optimizaciones para deploy
  .dockerignore
  .npmrc
  Dockerfile
  app/package.json
  package.json
  pnpm-lock.yaml
  scripts/package.json
  server/package.json
  turbo.json
Labels: enhancement, efficiency

#146 📝 Un poco de documentación
  README.md
  app/README.md
  server/README.md
Labels: documentation

#154 Se agrego logica para calcular los metadatos.
  app/package.json
  app/src/components/molecules/PlateMetadataForm.tsx
  app/src/components/molecules/SpectrumMetadataForm.tsx
  app/src/components/pages/StepMetadataRetrieval.tsx
  app/src/components/pages/StepPlateMetadata.tsx
  app/src/lib/calculateMetadata/AIRMASS.ts
  app/src/lib/calculateMetadata/calculateAllMetadata.ts
  app/src/lib/calculateMetadata/calculateRaDec.ts
  app/src/lib/calculateMetadata/epoca.ts
  app/src/lib/calculateMetadata/getSptypeMainidRa2000Dec2000.ts
  app/src/lib/calculateMetadata/hourAngle.ts
  app/src/lib/calculateMetadata/localTime.ts
  app/src/lib/calculateMetadata/sidereoTime.ts
  app/src/lib/calculateMetadata/toJulianDate.ts
  app/src/lib/observatories.ts
  app/src/lib/spectrumMetadataFormSchema.ts
  package.json
  pnpm-lock.yaml
Labels: enhancement, efficiency

#166 Se quito la logica de calcular los metadatos del front, y se agrego la consulta a la api.
  app/package.json
  app/src/components/pages/StepMetadataRetrieval.tsx
  app/src/lib/calculateMetadata/AIRMASS.ts
  app/src/lib/calculateMetadata/calculateAllMetadata.ts
  app/src/lib/calculateMetadata/calculateRaDec.ts
  app/src/lib/calculateMetadata/epoca.ts
  app/src/lib/calculateMetadata/getSptypeMainidRa2000Dec2000.ts
  app/src/lib/calculateMetadata/hourAngle.ts
  app/src/lib/calculateMetadata/localTime.ts
  app/src/lib/calculateMetadata/sidereoTime.ts
  app/src/lib/calculateMetadata/toJulianDate.ts
  app/src/lib/observatories.ts
  app/src/services/api/index.ts
  app/src/services/api/types.ts
  app/src/services/calculateMetadata/hooks.ts
  app/src/services/calculateMetadata/index.ts
  app/src/services/calculateMetadata/types.ts
  pnpm-lock.yaml
Labels: enhancement
